import React,{useEffect,useState} from 'react'; import API,{safeGet} from '../api'; import Toolbar from './Toolbar';
export default function Products(){ const [items,setItems]=useState([]); const [selected,setSelected]=useState(null); const [showForm,setShowForm]=useState(false); const [form,setForm]=useState({sku:'', name:''});
  useEffect(()=>load(),[]);
  async function load(q){ const res = await safeGet('/api/master/products','products'); setItems(res); }
  function newItem(){ setForm({sku:'',name:''}); setShowForm(true); }
  function editItem(){ if(!selected) return alert('Select row'); setForm(items.find(i=>i.id===selected)); setShowForm(true); }
  async function save(){ try{ if(form.id) await API.put(`/api/master/products/${form.id}`, form); else await API.post('/api/master/products', form); setShowForm(false); load(); }catch(e){ alert('Save failed') } }
  async function del(){ if(!selected) return alert('Select row'); if(!confirm('Delete?')) return; await API.delete(`/api/master/products/${selected}`); load(); }
  return (<div><div className='card'><h3>Products</h3><div style={{marginTop:8}}><button className='btn' onClick={()=>{window.open((import.meta.env.VITE_BACKEND_URL||'http://localhost:8000')+'/api/master/products/export?format=csv')}}>Export CSV</button><button className='btn' onClick={()=>{window.open((import.meta.env.VITE_BACKEND_URL||'http://localhost:8000')+'/api/master/products/export?format=xlsx')}}>Export XLSX</button></div><Toolbar onNew={newItem} onEdit={editItem} onDelete={del} onSearch={q=>API.get('/api/master/products',{params:{q}}).then(r=>setItems(r.data))} filterOptions={[{value:'contains',label:'Contains'}]} /><table className='table'><thead><tr><th></th><th>ID</th><th>SKU</th><th>Name</th><th>Unit Price</th><th>Unit Cost</th></tr></thead><tbody>{items.map(p=> <tr key={p.id} onClick={()=>setSelected(p.id)} style={{background:selected===p.id? 'rgba(255,255,255,0.03)':''}}><td><input type='radio' checked={selected===p.id} readOnly/></td><td>{p.id}</td><td>{p.sku}</td><td>{p.name}</td><td>{p.unit_price}</td><td>{p.unit_cost}</td></tr>)}</tbody></table></div>{showForm&&<div className='modal'><h4>{form.id? 'Edit Product':'New Product'}</h4><div style={{display:'grid',gap:8}}><input className='input' placeholder='SKU' value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/><input className='input' placeholder='Name' value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><div style={{display:'flex',gap:8,marginTop:8}}><button className='btn' onClick={save}>Save</button><button className='btn' onClick={()=>setShowForm(false)}>Cancel</button></div></div></div>}</div>); }
